# Generated by Django 4.2.7 on 2023-12-12 14:50

from django.db import migrations


def cargar_datos_iniciales(apps, schema_editor):
    Marca = apps.get_model('appCarOutlet', 'Marca')
    Categoria = apps.get_model('appCarOutlet', 'Categoria')
    Coche = apps.get_model('appCarOutlet', 'Coche')

    # Cargar Marcas
    marca1 = Marca(nombre='Ferrari')
    marca1.save()

    marca2 = Marca(nombre='Subaru')
    marca2.save()

    # Cargar Categorías
    categoria1 = Categoria(nombre='Turismo')
    categoria1.save()

    categoria2 = Categoria(nombre='Caravana')
    categoria2.save()

    # Cargar Coches
    coche1 = Coche(modelo='Ferrari F8', precio=10000, marca=marca1)
    coche1.save()
    coche1.categorias.set([categoria1, categoria2])

    coche2 = Coche(modelo='Subaru 34L', precio=15000, marca=marca2)
    coche2.save()
    coche2.categorias.set([categoria2])

class Migration(migrations.Migration):

    dependencies = [
        ('appCarOutlet', '0002_contacto'),
    ]

    operations = [
        migrations.RunPython(cargar_datos_iniciales),
    ]